# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_auto_20171223_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='chats', to='users.Profile', verbose_name='Participants'),
        ),
    ]
