# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.ManyToManyField(blank=True, related_name='blocked_by', to='users.Profile', verbose_name='Blocked users')),
                ('contacts', models.ManyToManyField(related_name='contact_of', to='users.Profile', verbose_name="User's contacts")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "User's profiles",
                'verbose_name_plural': 'Users profiles',
            },
        ),
    ]
