# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='contact_of', to='users.Profile', verbose_name="User's contacts"),
        ),
    ]
